version: 2
models: 
  - name: fct_orders
    columns:
      - name: order_id
        tests:
          - not_null
      - name: customer_unique_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_customers')
                field: customer_unique_id